"""
emailer.py — AI News Digest Emailer
Reads digest.md, converts to HTML email, sends to Gmail inbox.
"""

import os
import smtplib
import re
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# ── CONFIG ───────────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
DIGEST_FILE = os.path.join(BASE_DIR, "digest.md")
ENV_FILE    = os.path.join(BASE_DIR, ".env")
# ─────────────────────────────────────────────────────────────────────────────


def load_env():
    """Load credentials from .env file — handles UTF-16 encoding from Windows PowerShell."""
    if os.path.exists(ENV_FILE):
        raw     = open(ENV_FILE, "rb").read()
        cleaned = raw.replace(b"\xff\xfe", b"").replace(b"\xfe\xff", b"").replace(b"\x00", b"")
        for line in cleaned.decode("utf-8").strip().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                os.environ[k.strip()] = v.strip()


def markdown_to_html(md: str) -> str:
    """Convert markdown digest to clean HTML email."""

    html = md

    # Headers
    html = re.sub(r"^## (.+)$",   r"<h2>\1</h2>",   html, flags=re.MULTILINE)
    html = re.sub(r"^### (.+)$",  r"<h3>\1</h3>",   html, flags=re.MULTILINE)
    html = re.sub(r"^#### (.+)$", r"<h4>\1</h4>",   html, flags=re.MULTILINE)

    # Bold
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)

    # Italic
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)

    # Links [text](url)
    html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2" style="color:#0066cc;">\1</a>', html)

    # Bullet points
    html = re.sub(r"^- (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)
    html = re.sub(r"(<li>.*</li>\n?)+", r"<ul>\g<0></ul>", html, flags=re.DOTALL)

    # Numbered lists
    html = re.sub(r"^\d+\. (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)

    # Horizontal rules
    html = html.replace("---", "<hr style='border:none;border-top:1px solid #eee;margin:20px 0;'>")

    # Line breaks
    html = html.replace("\n\n", "</p><p>")
    html = f"<p>{html}</p>"

    return html


def build_email_html(digest_md: str) -> str:
    """Wrap the digest in a styled HTML email template."""
    body    = markdown_to_html(digest_md)
    today   = date.today().strftime("%d %B %Y")

    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f4f5f7;font-family:'Segoe UI',Arial,sans-serif;">

  <!-- WRAPPER -->
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f5f7;padding:32px 0;">
    <tr>
      <td align="center">
        <table width="640" cellpadding="0" cellspacing="0" style="max-width:640px;width:100%;">

          <!-- HEADER -->
          <tr>
            <td style="background:linear-gradient(135deg,#1a1a2e,#16213e);padding:28px 32px;border-radius:12px 12px 0 0;">
              <h1 style="margin:0;color:#e8b84b;font-size:20px;font-weight:700;">🗞️ Weekly AI Digest</h1>
              <p style="margin:6px 0 0;color:#aaaacc;font-size:13px;">{today} · Powered by Claude AI</p>
            </td>
          </tr>

          <!-- BODY -->
          <tr>
            <td style="background:#ffffff;padding:28px 32px;border-radius:0 0 12px 12px;font-size:14px;color:#333;line-height:1.7;">
              {body}
            </td>
          </tr>

          <!-- FOOTER -->
          <tr>
            <td style="padding:16px 0;text-align:center;font-size:11px;color:#999;">
              Auto-generated by your AI News Digest Agent ·
              <a href="https://github.com/SatyajeetBhosale/nz-job-application-tool" style="color:#999;">GitHub</a>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>
</html>"""


def send_email(subject: str, html_body: str, sender: str, password: str, receiver: str):
    """Send HTML email via Gmail SMTP."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = sender
    msg["To"]      = receiver

    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, receiver, msg.as_string())


def main():
    load_env()

    sender   = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")

    if not all([sender, password, receiver]):
        print("❌ Email credentials missing in .env file.")
        print("   Make sure EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECEIVER are set.")
        exit(1)

    if not os.path.exists(DIGEST_FILE):
        print("❌ digest.md not found. Run summariser.py first.")
        exit(1)

    print("\n📧 AI News Emailer\n")

    # Read digest
    with open(DIGEST_FILE, "r", encoding="utf-8") as f:
        digest_md = f.read()

    # Build email
    today   = date.today().strftime("%d %B %Y")
    subject = f"🗞️ Weekly AI Digest — {today}"
    html    = build_email_html(digest_md)

    # Send
    print(f"   Sending to {receiver}...")
    try:
        send_email(subject, html, sender, password, receiver)
        print(f"✅ Email sent successfully!")
        print(f"   Subject: {subject}")
        print(f"   Check your inbox at {receiver}")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        print("\n   Common fixes:")
        print("   - Check your Gmail App Password is correct in .env")
        print("   - Make sure 2-Step Verification is ON in your Google account")
        print("   - Check you used an App Password, not your normal Gmail password")


if __name__ == "__main__":
    main()
